In [2]:
import sys
sys.path.append("../src")

In [3]:
from database_connection import DatabaseConnector
from queries_descreptive import NBAPlayerExtractionQuaries
from data_loader_descreptive import NBADataLoader
from Statical_Analysis import StaticalAnalysis

In [4]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import shapiro, mannwhitneyu
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [ ]:
db = DatabaseConnector(\.env")
engine = db.create_connection()

In [6]:
loader = NBADataLoader(engine)

df_top50league_players = loader.load_top50_league_players(NBAPlayerExtractionQuaries.query_top50_league_players)
df_michel_jordan_trophy_list = loader.load_michel_jordan_list(NBAPlayerExtractionQuaries.query_micheljordan_tropy_list)
df_champions_top15_experience = loader.load_champion_top15_experience(NBAPlayerExtractionQuaries.query_champions_top15_experience)
df_champions_top15_height = loader.load_champion_top15_height(NBAPlayerExtractionQuaries.query_champions_top15_height)
df_suggested_players = loader.load_suggested_players(NBAPlayerExtractionQuaries.query_suggested_players)
df_top15league_players_height = loader.load_top15_league_players_height(NBAPlayerExtractionQuaries.query_top15_league_players_height)
df_top15league_players_experience = loader.load_top15_league_players_experience(NBAPlayerExtractionQuaries.query_top15_league_players_experience)

In [7]:
df_top50league_players.head()

   player_id               fullname  height  total_performance_index
0       1231       Domantas Sabonis    82.0                  22474.5
1       3473           James Harden    77.0                  22422.0
2        120  Giannis Antetokounmpo    83.0                  21394.0
3       3823         Andre Drummond    83.0                  19835.0
4       4344          Pascal Siakam    80.0                  19353.0

In [8]:
df_top50league_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   player_id                50 non-null     int64
 1   fullname                 50 non-null     object
 2   height                   50 non-null     float64
 3   total_performance_index  50 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 1.7+ KB

In [9]:
df_michel_jordan_trophy_list.head()

   player_id               fullname  height season_years mvp_award_name
0       3085           LeBron James    81.0    2017-2018          MVP-2
1       3473           James Harden    77.0    2017-2018          MVP-1
2       1074          Anthony Davis    82.0    2017-2018          MVP-3
3       5072      Russell Westbrook    76.0    2017-2018          MVP-5
4        120  Giannis Antetokounmpo    83.0    2017-2018          MVP-6

In [10]:
df_michel_jordan_trophy_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player_id       92 non-null     int64
 1   fullname        92 non-null     object
 2   height          92 non-null     float64
 3   season_years    92 non-null     object
 4   mvp_award_name  92 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 3.7+ KB

In [11]:
df_champions_top15_experience.head()

,player_id,fullname,experience_years,season_years,team_name,performance_index
0,3146,Kyrie Irving,6,2022-2023,Dallas Mavericks,5865.0
1,1596,Jakob Poeltl,6,2022-2023,Toronto Raptors,5659.0
2,1203,Spencer Dinwiddie,6,2022-2023,Dallas Mavericks,5619.0
3,3419,Josh Hart,6,2022-2023,Portland Trail Blazers,5148.0
4,1231,Domantas Sabonis,6,2022-2023,Sacramento Kings,4397.5

In [12]:
df_champions_top15_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   player_id          30 non-null     int64
 1   fullname           30 non-null     object
 2   experience_years   30 non-null     int64
 3   season_years       30 non-null     object
 4   team_name          30 non-null     object
 5   performance_index  30 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 1.5+ KB

In [13]:
df_champions_top15_height.head()

,player_id,fullname,height,season_years,team_name,performance_index
0,3146,Kyrie Irving,74.0,2022-2023,Dallas Mavericks,5865.0
1,1596,Jakob Poeltl,84.0,2022-2023,Toronto Raptors,5659.0
2,1203,Spencer Dinwiddie,77.0,2022-2023,Dallas Mavericks,5619.0
3,3419,Josh Hart,77.0,2022-2023,Portland Trail Blazers,5148.0
4,1231,Domantas Sabonis,82.0,2022-2023,Sacramento Kings,4397.5

In [14]:
df_champions_top15_height.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   player_id          30 non-null     int64
 1   fullname           30 non-null     object
 2   height             30 non-null     float64
 3   season_years       30 non-null     object
 4   team_name          30 non-null     object
 5   performance_index  30 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.5+ KB

In [15]:
df_suggested_players.head()

   player_id        fullname  mvp_nomination_count
0       1036   Stephen Curry                     3
1       1703      Chris Paul                     3
2        618   Jalen Brunson                     2
3       2057       Ja Morant                     2
4       2561  Damian Lillard                     2

In [16]:
df_suggested_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             13 non-null     int64
 1   fullname              13 non-null     object
 2   mvp_nomination_count  13 non-null     int64
dtypes: int64(2), object(1)
memory usage: 444.0+ bytes

In [17]:
#comparing distribution of height for top 50 players of the league and michael jordan trophy nominations for seasons 2019-2024
analyzer = StaticalAnalysis(df_top50league_players, df_michel_jordan_trophy_list)
analyzer.plot_kde_boxplot_side_by_side(
    col1="height",
    label1="Top 50 League Players",
    label2="MJ Trophy List"
)

In [18]:
# checking if there is meaningful difference between the heights of the top 50 players of the league and michel jordan trophy nominations for seasons 2019-2024
analyzer = StaticalAnalysis(df1=df_top50league_players, df2=df_michel_jordan_trophy_list)
test_result = analyzer.smart_hypothesis_test(col1="height", col2="height")
print(test_result)

{'test_used': 'Mann-Whitney U test', 'statistic': np.float64(2213.5), 'p_value': np.float64(0.7116567490645225), 'normality_p_values': (np.float64(0.17533223012246457), np.float64(0.0004279509375580663))}

In [19]:
analyzer = StaticalAnalysis(df_top15league_players_height, df_champions_top15_height)
analyzer.plot_kde_boxplot_side_by_side(
    col1="height",
    label1="Top 15 League Players",
    label2="MJ Trophy List"
)

In [25]:
analyzer = StaticalAnalysis(df1=df_top15league_players_height, df2=df_champions_top15_height)
test_result = analyzer.smart_hypothesis_test(col1="height" , col2 = "height")
print(test_result)

{'test_used': 'Independent t-test', 'statistic': np.float64(1.9770352541172596), 'p_value': np.float64(0.05447212247021685), 'normality_p_values': (np.float64(0.23724257139009935), np.float64(0.05430298551206215))}

In [20]:
analyzer = StaticalAnalysis(df_top15league_players_experience, df_champions_top15_experience)
analyzer.plot_kde_boxplot_side_by_side(
    col1="experience_years",
    label1="Top 15 League Players",
    label2="Top 15 Champion Players"
)

In [21]:
df_top15league_players_experience['experience_years'].value_counts()

experience_years
5    20
3    17
4    16
6    12
7     8
2     1
1     1
Name: count, dtype: int64

In [24]:
#cheking whether if there is meaningful difference between the height and exprience in distributions
analyzer = StaticalAnalysis(df1=df_top15league_players_experience, df2=df_champions_top15_experience)
test_result = analyzer.smart_hypothesis_test(col1="experience_years" , col2 = "experience_years")
print(test_result)

{'test_used': 'Mann-Whitney U test', 'statistic': np.float64(709.5), 'p_value': np.float64(0.002642842778198339), 'normality_p_values': (np.float64(0.0005973728532609175), np.float64(0.00044063431961713676))}

In [ ]:
#suggestion for the 3 players in point guard position based on their stats
analyzer = StaticalAnalysis(df1=df_suggested_players, df2=None)
top_players = analyzer.plot_top_players(name_column="fullname", value_column="mvp_nomination_count")
print(top_players)

                   fullname  mvp_nomination_count
7              Devin Booker                     1
10             De'Aaron Fox                     1
9          Donovan Mitchell                     1
12        Russell Westbrook                     1
11              Ben Simmons                     1
8              Derrick Rose                     1
4            Damian Lillard                     2
3                 Ja Morant                     2
2             Jalen Brunson                     2
5              James Harden                     2
6   Shai Gilgeous-Alexander                     2
0             Stephen Curry                     3
1                Chris Paul                     3